- name: Install mysql server
  apt: name=mysql-server state=present
  when: relational_database == "mysql"
  tags:
  - appliance

- name: Install mariadb server
  apt: name=mariadb-server state=present
  when: relational_database == "mariadb"
  tags:
  - appliance

- name: Ensure mysql/mariadb is started
  service: name=mysql state=started
  when: relational_database == "mysql" or relational_database == "mariadb"


- name: Configure mysql server
  template: src=mysqld_taiga.cnf.j2 dest=/etc/mysql/conf.d/mysqld_taiga.cnf
  notify: restart mysql
  when: relational_database == "mysql"

- name: Configure mariadb server
  template: src=mysqld_taiga.cnf.j2 dest=/etc/mysql/mariadb.conf.d/mysqld_taiga.cnf
  notify: restart mysql
  when: relational_database == "mariadb"

- name: Install python-mysqldb
  apt: name=python-mysqldb state=present
  when: relational_database == "mysql" or relational_database == "mariadb"
  tags:
  - appliance

- name: Install Postgresql
  apt: name=postgresql state=present
  when: relational_database == "postgresql"
  tags:
  - appliance

#- name: Ensure postgresql is started
#  service: name=postgresql state=restarted

# TODO: please, obtain cidr from: `sipcalc ose | grep "Network mask" | grep bits | awk '{print $NF}'`

- name: Configure access from management networking
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.5/main/pg_hba.conf owner=postgres group=postgres mode=0640
  notify: restart postgresql
  when: relational_database == "postgresql"

- name: Configure listening address interface
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.5/main/postgresql.conf owner=postgres group=postgres mode=0644
  notify: restart postgresql
  when: relational_database == "postgresql"

- name: Install python postgresql client
  apt: name=python-psycopg2 state=present
  when: relational_database == "postgresql"
  tags:
  - appliance

- meta: flush_handlers

- name: Create mysql based database
  mysql_db: name={{ taiga_database_name }} state=present
  when: relational_database == "mysql" or relational_database == "mariadb"

- name: Create mysql based database user to localhost
  mysql_user: name={{ taiga_database_username }} host=localhost password={{ taiga_database_password }} priv={{ taiga_database_name }}.*:ALL,GRANT state=present
  when: relational_database == "mysql" or relational_database == "mariadb"

- name: Create mysql based database user to %
  mysql_user: name={{ taiga_database_username }} host=% password={{ taiga_database_password }} append_privs=yes priv={{ taiga_database_name }}.*:ALL,GRANT state=present
  when: relational_database == "mysql" or relational_database == "mariadb"

# postgresql
- name: Create postgresql database
  postgresql_db: name={{ taiga_database_name }}
  when: relational_database == "postgresql"

- name: Create postgresql database user
  postgresql_user: db={{ taiga_database_name }} name={{ taiga_database_username }} password={{ taiga_database_password }} priv=ALL
  when: relational_database == "postgresql"
