- name: Install rabbitmq server
  apt: name=rabbitmq-server state=present
  tags:
  - appliance

- name: Setup rabbitmq nodename
  template: src=rabbitmq-env.conf.j2 dest=/etc/rabbitmq/rabbitmq-env.conf owner=rabbitmq group=rabbitmq mode=0644
  notify:
  - restart rabbitmq-server

- meta: flush_handlers

- name: Create vhost
  rabbitmq_vhost:
    name={{ rabbitmq_vhost }}
    state=present
    node={{ rabbitmq_hostname }}

- name: Create rabbitmq user
  rabbitmq_user:
    user={{ rabbitmq_user }}
    password={{ rabbitmq_password }}
    vhost={{ rabbitmq_vhost }}
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present
    force=yes
    node={{ rabbitmq_hostname }}
  notify: restart rabbitmq-server
