- name: Install rabbitmq server
  apt: name=rabbitmq-server state=present
  tags:
  - appliance

- name: Create vhost
  rabbitmq_vhost:
    name={{ rabbitmq_vhost }}
    state=present

- name: Create openstack rabbitmq user
  rabbitmq_user:
    user={{ rabbitmq_user }}
    password={{ rabbitmq_password }}
    vhost={{ rabbitmq_vhost }}
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present
  notify: restart rabbitmq-server
